# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe64184ae9f3939f56a278b3532376222d67a5020ea708335cc7b2134c51c7f5563d6d819d0704a45a56a88f74bd8cd555ae51c1a1f908774cf8bad8ad003b58

test:
  secret_key_base: c2941f1264d5264921ef3141e3cd3c0799b71d8ec05cf30fb1ec991d10d3d49d6f7b2f780252faf10780e1d75cf6a338d2ce06dc5afbc9504c949355a3a1c492

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
